package Vue;

import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JLabel;

import Controlleur.Controlleur;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.CardLayout;
import java.awt.GridBagLayout;
import javax.swing.JTextField;
import javax.swing.JButton;

public class Vue extends JFrame{

	 Controlleur mycontrolleur;
	    /**
	     * Creates new form Fenetre
	     */
	    public Vue(Controlleur controlleur) {
	        mycontrolleur = controlleur;
	        initComponents();
	        
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        plusconsigne = new javax.swing.JButton();
	        moinsconsigne = new javax.swing.JButton();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        tempValue = new javax.swing.JLabel();
	        humidityValue = new javax.swing.JLabel();
	        consigne = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        plusconsigne.setText("+");
	        plusconsigne.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                plusconsigneActionPerformed(evt);
	            }
	        });

	        moinsconsigne.setText("-");
	        moinsconsigne.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                moinsconsigneActionPerformed(evt);
	            }
	        });

	        jLabel1.setText("Humidité en % :");

	        jLabel2.setText("Température en °C : ");

	        jLabel3.setText("Température de consigne :");

	        tempValue.setText("0 °C");

	        humidityValue.setText("0 %");

	        consigne.setText("10 °C");

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(58, 58, 58)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(plusconsigne)
	                        .addGap(18, 18, 18)
	                        .addComponent(moinsconsigne))
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jLabel3)
	                        .addGap(18, 18, 18)
	                        .addComponent(consigne))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(tempValue)
	                            .addComponent(humidityValue))))
	                .addContainerGap(35, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addGap(46, 46, 46)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(tempValue))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(humidityValue))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(consigne))
	                .addGap(30, 30, 30)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(plusconsigne)
	                    .addComponent(moinsconsigne))
	                .addContainerGap(33, Short.MAX_VALUE))
	        );

	        pack();
	    }// </editor-fold>//GEN-END:initComponents

	    private void plusconsigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusconsigneActionPerformed
	        // TODO add your handling code here:
	        
	       mycontrolleur.plusConsigne(consigne.getText());
	      // oldTemp[0]
	    }//GEN-LAST:event_plusconsigneActionPerformed

	    private void moinsconsigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moinsconsigneActionPerformed
	        // TODO add your handling code here:
	        mycontrolleur.moinsConsigne(consigne.getText());
	    }//GEN-LAST:event_moinsconsigneActionPerformed

	    /**
	     * @param args the command line arguments
	     */

	    public javax.swing.JLabel getHumidityValue() {
	        return humidityValue;
	    }

	    public void setHumidityValue(double newValue) {
	        this.humidityValue.setText(newValue+" %");
	    }

	    public javax.swing.JLabel getTempValue() {
	        return tempValue;
	    }

	    public void setTempValue(double newValue) {
	        tempValue.setText(newValue+" °C");
	    }
	    

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JLabel consigne;
	    private javax.swing.JLabel humidityValue;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JButton moinsconsigne;
	    private javax.swing.JButton plusconsigne;
	    private javax.swing.JLabel tempValue;
	    // End of variables declaration//GEN-END:variables

	    public javax.swing.JLabel getConsigne() {
	        return consigne;
	    }

	    public void setConsigne(double newConsigne) {
	        consigne.setText(newConsigne + " °C");
	}
}
